Import-Module -Name .\EulandaConnect.psd1
Set-StrictMode -version latest

Describe 'Test-ShopExtension' -Tag 'integration', 'sql', 'sqladmin', 'eulanda' {

    BeforeAll {
        $udl = Resolve-Path ".\source\tests\Eulanda_1 Pester.udl"

        # Test-MssqlAdministartor rights
        $skipTest = -not (Test-MssqlAdministrator -udl $udl)

        # Skip backup because for restoring you need special rights
        if (! $skipTest) {
            Backup-MssqlDatabase -udl $udl

            . source\tests\include\Include-InsertArticle.ps1


            $sqlShop = @"
            /*
            Generated by EulCMD.exe - (c) 2011 EULANDA Software GmbH - www.eulanda.de
            Create date (year/month/day): 2014/3/22
            */


            --  CREATE TABLE esolArtikelShop
            --  ============================
            IF OBJECT_ID('esolArtikelShop') IS NULL
             CREATE TABLE esolArtikelShop
              (
                id int NOT NULL
                  CONSTRAINT PK_esolArtikelShop PRIMARY KEY
                  CONSTRAINT FK_esolArtikelShop_AR FOREIGN KEY
                    REFERENCES dbo.Artikel (id) ON DELETE CASCADE
              )


            --  CREATE FIELD ArticleType int NOT NULL Default(0)
            --  ================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'ArticleType'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD ArticleType int NOT NULL Constraint DF_esolArtikelShop_ArticleType Default(0)
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'ArticleType') <> 'ArticleType int'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN ArticleType int NOT NULL


            --  CREATE FIELD MasterArticle varchar(64) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'MasterArticle'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD MasterArticle varchar(64) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'MasterArticle') <> 'MasterArticle varchar(64)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN MasterArticle varchar(64) NULL


            --  CREATE FIELD MetaTitle varchar(128) NULL
            --  =========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'MetaTitle'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD MetaTitle varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'MetaTitle') <> 'MetaTitle varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN MetaTitle varchar(128) NULL


            --  CREATE FIELD MetaDescription varchar(max) NULL
            --  ===============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'MetaDescription'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD MetaDescription varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'MetaDescription') <> 'MetaDescription varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN MetaDescription varchar(max) NULL


            --  CREATE FIELD MetaKeywords varchar(max) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'MetaKeywords'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD MetaKeywords varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'MetaKeywords') <> 'MetaKeywords varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN MetaKeywords varchar(max) NULL


            --  CREATE FIELD DimensionHeight int NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'DimensionHeight'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD DimensionHeight int NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'DimensionHeight') <> 'DimensionHeight int'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN DimensionHeight int NULL


            --  CREATE FIELD DimensionWidth int NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'DimensionWidth'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD DimensionWidth int NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'DimensionWidth') <> 'DimensionWidth int'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN DimensionWidth int NULL


            --  CREATE FIELD DimensionDepth int NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'DimensionDepth'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD DimensionDepth int NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'DimensionDepth') <> 'DimensionDepth int'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN DimensionDepth int NULL


            --  CREATE FIELD InfoURLText varchar(64) NULL
            --  ==========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'InfoURLText'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD InfoURLText varchar(64) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'InfoURLText') <> 'InfoURLText varchar(64)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN InfoURLText varchar(64) NULL


            --  CREATE FIELD InfoURL varchar(128) NULL
            --  =======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'InfoURL'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD InfoURL varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'InfoURL') <> 'InfoURL varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN InfoURL varchar(128) NULL


            --  CREATE FIELD Image1 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image1'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image1 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image1') <> 'Image1 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image1 varchar(128) NULL


            --  CREATE FIELD Image2 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image2'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image2 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image2') <> 'Image2 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image2 varchar(128) NULL


            --  CREATE FIELD Image3 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image3'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image3 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image3') <> 'Image3 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image3 varchar(128) NULL


            --  CREATE FIELD Image4 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image4'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image4 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image4') <> 'Image4 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image4 varchar(128) NULL


            --  CREATE FIELD Image5 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image5'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image5 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image5') <> 'Image5 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image5 varchar(128) NULL


            --  CREATE FIELD Image6 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image6'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image6 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image6') <> 'Image6 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image6 varchar(128) NULL


            --  CREATE FIELD Image7 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image7'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image7 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image7') <> 'Image7 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image7 varchar(128) NULL


            --  CREATE FIELD Image8 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image8'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image8 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image8') <> 'Image8 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image8 varchar(128) NULL


            --  CREATE FIELD Image9 varchar(128) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image9'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image9 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image9') <> 'Image9 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image9 varchar(128) NULL


            --  CREATE FIELD Image10 varchar(128) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image10'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image10 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image10') <> 'Image10 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image10 varchar(128) NULL


            --  CREATE FIELD Image11 varchar(128) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image11'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image11 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image11') <> 'Image11 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image11 varchar(128) NULL


            --  CREATE FIELD Image12 varchar(128) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image12'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image12 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image12') <> 'Image12 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image12 varchar(128) NULL


            --  CREATE FIELD Image13 varchar(128) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image13'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image13 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image13') <> 'Image13 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image13 varchar(128) NULL


            --  CREATE FIELD Image14 varchar(128) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image14'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image14 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image14') <> 'Image14 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image14 varchar(128) NULL


            --  CREATE FIELD Image15 varchar(128) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Image15'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Image15 varchar(128) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Image15') <> 'Image15 varchar(128)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Image15 varchar(128) NULL


            --  CREATE FIELD SuggestedListPrice numeric(18,2) NULL
            --  ===================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'SuggestedListPrice'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD SuggestedListPrice numeric(18,2) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'SuggestedListPrice') <> 'SuggestedListPrice numeric(18,2)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN SuggestedListPrice numeric(18,2) NULL


            --  CREATE FIELD VariantText1 varchar(25) NULL
            --  ===========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantText1'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantText1 varchar(25) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantText1') <> 'VariantText1 varchar(25)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantText1 varchar(25) NULL


            --  CREATE FIELD VariantText2 varchar(25) NULL
            --  ===========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantText2'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantText2 varchar(25) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantText2') <> 'VariantText2 varchar(25)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantText2 varchar(25) NULL


            --  CREATE FIELD VariantText3 varchar(25) NULL
            --  ===========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantText3'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantText3 varchar(25) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantText3') <> 'VariantText3 varchar(25)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantText3 varchar(25) NULL


            --  CREATE FIELD VariantText4 varchar(25) NULL
            --  ===========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantText4'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantText4 varchar(25) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantText4') <> 'VariantText4 varchar(25)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantText4 varchar(25) NULL


            --  CREATE FIELD VariantText5 varchar(25) NULL
            --  ===========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantText5'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantText5 varchar(25) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantText5') <> 'VariantText5 varchar(25)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantText5 varchar(25) NULL


            --  CREATE FIELD VariantDimensions1 varchar(max) NULL
            --  ==================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantDimensions1'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantDimensions1 varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantDimensions1') <> 'VariantDimensions1 varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantDimensions1 varchar(max) NULL


            --  CREATE FIELD VariantDimensions2 varchar(max) NULL
            --  ==================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantDimensions2'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantDimensions2 varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantDimensions2') <> 'VariantDimensions2 varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantDimensions2 varchar(max) NULL


            --  CREATE FIELD VariantDimensions3 varchar(max) NULL
            --  ==================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantDimensions3'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantDimensions3 varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantDimensions3') <> 'VariantDimensions3 varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantDimensions3 varchar(max) NULL


            --  CREATE FIELD VariantDimensions4 varchar(max) NULL
            --  ==================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantDimensions4'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantDimensions4 varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantDimensions4') <> 'VariantDimensions4 varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantDimensions4 varchar(max) NULL


            --  CREATE FIELD VariantDimensions5 varchar(max) NULL
            --  ==================================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantDimensions5'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantDimensions5 varchar(max) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantDimensions5') <> 'VariantDimensions5 varchar(max)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantDimensions5 varchar(max) NULL


            --  CREATE FIELD VariantValue1 varchar(32) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantValue1'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantValue1 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantValue1') <> 'VariantValue1 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantValue1 varchar(32) NULL


            --  CREATE FIELD VariantValue2 varchar(32) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantValue2'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantValue2 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantValue2') <> 'VariantValue2 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantValue2 varchar(32) NULL


            --  CREATE FIELD VariantValue3 varchar(32) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantValue3'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantValue3 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantValue3') <> 'VariantValue3 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantValue3 varchar(32) NULL


            --  CREATE FIELD VariantValue4 varchar(32) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantValue4'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantValue4 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantValue4') <> 'VariantValue4 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantValue4 varchar(32) NULL


            --  CREATE FIELD VariantValue5 varchar(32) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'VariantValue5'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD VariantValue5 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'VariantValue5') <> 'VariantValue5 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN VariantValue5 varchar(32) NULL


            --  CREATE FIELD Cross1 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross1'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross1 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross1') <> 'Cross1 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross1 varchar(32) NULL


            --  CREATE FIELD Cross2 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross2'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross2 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross2') <> 'Cross2 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross2 varchar(32) NULL


            --  CREATE FIELD Cross3 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross3'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross3 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross3') <> 'Cross3 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross3 varchar(32) NULL


            --  CREATE FIELD Cross4 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross4'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross4 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross4') <> 'Cross4 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross4 varchar(32) NULL


            --  CREATE FIELD Cross5 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross5'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross5 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross5') <> 'Cross5 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross5 varchar(32) NULL


            --  CREATE FIELD Cross6 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross6'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross6 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross6') <> 'Cross6 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross6 varchar(32) NULL


            --  CREATE FIELD Cross7 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross7'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross7 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross7') <> 'Cross7 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross7 varchar(32) NULL


            --  CREATE FIELD Cross8 varchar(32) NULL
            --  =====================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Cross8'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Cross8 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Cross8') <> 'Cross8 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Cross8 varchar(32) NULL


            --  CREATE FIELD Up1 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up1'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up1 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up1') <> 'Up1 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up1 varchar(32) NULL


            --  CREATE FIELD Up2 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up2'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up2 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up2') <> 'Up2 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up2 varchar(32) NULL


            --  CREATE FIELD Up3 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up3'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up3 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up3') <> 'Up3 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up3 varchar(32) NULL


            --  CREATE FIELD Up4 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up4'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up4 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up4') <> 'Up4 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up4 varchar(32) NULL


            --  CREATE FIELD Up5 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up5'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up5 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up5') <> 'Up5 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up5 varchar(32) NULL


            --  CREATE FIELD Up6 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up6'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up6 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up6') <> 'Up6 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up6 varchar(32) NULL


            --  CREATE FIELD Up7 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up7'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up7 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up7') <> 'Up7 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up7 varchar(32) NULL


            --  CREATE FIELD Up8 varchar(32) NULL
            --  ==================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'Up8'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD Up8 varchar(32) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'Up8') <> 'Up8 varchar(32)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN Up8 varchar(32) NULL


            --  CREATE FIELD BaseDivisor numeric(18,4) NULL
            --  ============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'BaseDivisor'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD BaseDivisor numeric(18,4) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'BaseDivisor') <> 'BaseDivisor numeric(18,4)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN BaseDivisor numeric(18,4) NULL


            --  CREATE FIELD BaseUnit varchar(8) NULL
            --  ======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'BaseUnit'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD BaseUnit varchar(8) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'BaseUnit') <> 'BaseUnit varchar(8)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN BaseUnit varchar(8) NULL


            --  CREATE FIELD SalesSize numeric(18,4) NULL
            --  ==========================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'SalesSize'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD SalesSize numeric(18,4) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'SalesSize') <> 'SalesSize numeric(18,4)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN SalesSize numeric(18,4) NULL


            --  CREATE FIELD SalesUnit varchar(8) NULL
            --  =======================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'SalesUnit'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD SalesUnit varchar(8) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'SalesUnit') <> 'SalesUnit varchar(8)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN SalesUnit varchar(8) NULL


            --  CREATE FIELD ShippingWeight numeric(18,4) NULL
            --  ===============================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'ShippingWeight'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD ShippingWeight numeric(18,4) NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'ShippingWeight') <> 'ShippingWeight numeric(18,4)'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN ShippingWeight numeric(18,4) NULL


            --  CREATE FIELD ShippingFree bit NULL
            --  ===================================
            IF NOT EXISTS (SELECT * FROM sys.Columns WHERE Name = 'ShippingFree'
                AND object_id = object_id('esolArtikelShop'))
              ALTER TABLE esolArtikelShop
                ADD ShippingFree bit NULL
            ELSE IF (SELECT dbo.cnf_SqlVarDeclare(name, system_type_id, precision, scale)
                            FROM sys.Columns WHERE object_id = object_id('dbo.esolArtikelShop')
                                              AND Name = 'ShippingFree') <> 'ShippingFree bit'
                   ALTER TABLE esolArtikelShop
                   ALTER COLUMN ShippingFree bit NULL


            IF OBJECT_ID('ESOL_MASTER_Artikel_Shop') IS NULL
            exec ('CREATE VIEW ESOL_MASTER_Artikel_Shop as select dummy=1')

            exec('
            ALTER VIEW [ESOL_MASTER_Artikel_Shop]
            with view_metadata
            as
            SELECT
            art.*, arts.ArticleType, arts.BaseDivisor, arts.BaseUnit,
            arts.Cross1, arts.Cross2, arts.Cross3, arts.Cross4, arts.Cross5, arts.Cross6, arts.Cross7, arts.Cross8,
            arts.DimensionDepth, arts.DimensionHeight, arts.DimensionWidth,
            arts.Image1, arts.Image2, arts.Image3, arts.Image4, arts.Image5, arts.Image6, arts.Image7, arts.Image8, arts.Image9,
            arts.Image10, arts.Image11, arts.Image12, arts.Image13, arts.Image14, arts.Image15,
            arts.InfoUrl, arts.InfoUrlText,
            arts.MasterArticle, arts.MetaDescription, arts.MetaKeywords, arts.MetaTitle,
            arts.SalesSize, arts.SalesUnit, arts.ShippingFree, arts.ShippingWeight, arts.SuggestedListPrice,
            arts.up1, arts.up2, arts.up3, arts.up4, arts.up5, arts.up6, arts.up7, arts.up8,
            arts.VariantDimensions1, arts.VariantDimensions2, arts.VariantDimensions3, arts.VariantDimensions4, arts.VariantDimensions5,
            arts.VariantText1, arts.VariantText2, arts.VariantText3, arts.VariantText4, arts.VariantText5,
            arts.VariantValue1, arts.VariantValue2, arts.VariantValue3, arts.VariantValue4, arts.VariantValue5
             FROM MASTER_Artikel art
            LEFT JOIN esolArtikelShop arts ON art.id = arts.id
            ')

            if OBJECT_ID('dbo.cnf_custom_shop_artikel_info') IS NULL
            EXEC ('CREATE function [dbo].[cnf_custom_shop_artikel_info](@sku varchar(100))
            returns varchar(max)
            as
            begin
              declare @Artikelid int;
              declare @de varchar(max), @it varchar(max),  @en varchar(max), @fr varchar(max), @xx varchar(max);
              declare @t varchar(max);
              declare @pat varchar(10);
              declare @value varchar(max);

              SELECT @Artikelid = ID FROM Artikel WHERE ArtNummer = @sku

              SET @pat = ''%[^ '' + char(09) + char(10) + char(13) + '']%''
              select @value = IsNull(Info,'''') from Artikel where id = @Artikelid;
              select @xx = @value
              set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2)
              set @t = @value

            --  while right(@t,2) = CHAR(13)+CHAR(10)
            --  begin
            --    set @t = Left(@t, len(@t) -2)
            --  end;

              set @de = '''';
              set @it = '''';
              set @en = '''';
              set @fr = '''';


              if @t <> ''''
              begin
                set @value = IsNull(dbo.cnf_extractSubField(@t, ''DE''),'''');
                set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2)
                set @de = @value

                set @value = isnull(dbo.cnf_extractSubField(@t, ''IT''),'''');
                set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2)
                set @it = @value

                set @value = isnull(dbo.cnf_extractSubField(@t, ''EN''),'''');
                set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2)
                set @en = @value

                set @value = IsNull(dbo.cnf_extractSubField(@t, ''FR''),'''');
                set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2)
                set @de = @value

              end;



              declare c cursor local static for
              select m.Beschreibung
                from merkmalelement me
                join Merkmal m on m.id=me.kopfid
                where me.objektid = @ArtikelId
                  and m.Tabelle=''Artikel''
                  and m.ParentId = 196
                order by m.name;

              open c;

              fetch next from c into @T;
              while @@fetch_status = 0
              begin
                if IsNull(@t, '''') <> ''''
                begin
                  set @value = isnull(dbo.cnf_extractSubField(@t, ''DE''),'''');
                  set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2);
                  if @value = '''' set @value = null;
                  if @de <>'''' set @de +=  isnull(CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10)+@value, '''') else set @de = isnull(@value, '''');

                  set @value = isnull(dbo.cnf_extractSubField(@t, ''IT''),'''');
                  set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2);
                  if @value = '''' set @value = null;
                  if @it <>'''' set @it +=  isnull(CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10)+@value, '''') else set @it = isnull(@value, '''');

                  set @value = isnull(dbo.cnf_extractSubField(@t, ''EN''),'''');
                  set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2);
                  if @value = '''' set @value = null;
                  if @en <>'''' set @en +=  isnull(CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10)+@value, '''') else set @en = isnull(@value, '''');

                  set @value = isnull(dbo.cnf_extractSubField(@t, ''FR''),'''');
                  set @value = SUBSTRING(@value, PATINDEX(@pat, @value), LEN(@value) - PATINDEX(@pat, @value) - PATINDEX(@pat, REVERSE(@value)) + 2);
                  if @value = '''' set @value = null;
                  if @fr <>'''' set @fr +=  isnull(CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10)+@value, '''') else set @fr = isnull(@value, '''');

                  set @value = @t
                  if @xx <>'''' set @xx +=  isnull(CHAR(13)+CHAR(10)+CHAR(13)+CHAR(10)+@value, '''') else set @xx = isnull(@value, '''');

                end

                fetch next from c into @T;
              end;

              if @de <> '''' set @de += CHAR(13)+CHAR(10);
              if @it <> '''' set @it += CHAR(13)+CHAR(10);
              if @en <> '''' set @en += CHAR(13)+CHAR(10);
              if @fr <> '''' set @fr += CHAR(13)+CHAR(10);
              if @xx <> '''' set @xx += CHAR(13)+CHAR(10);
              set @t = ''[DE]''+CHAR(13)+CHAR(10)+@de+''[IT]''+CHAR(13)+CHAR(10)+@it+''[FR]''+CHAR(13)+CHAR(10)+@fr+''[EN]''+CHAR(13)+CHAR(10)+@en;
              if @de = '''' and @it = '''' and @fr = '''' and @en = '''' and @xx <> '''' set @t = @xx;
              set @t = IsNull(@t, '''')
              return( @t)
            end;')




            --drop table esolShopBestandQueue
            if OBJECT_ID('[dbo].[esolShopBestandQueue]') is null
            exec ('CREATE TABLE [dbo].[esolShopBestandQueue](
                [id] [int] IDENTITY(1,1) NOT NULL,
                [ArtikelId] [int] NOT NULL,
                [changedate] [datetime] NOT NULL CONSTRAINT [DF_esolShopBestandQueue_ChangeDate]  DEFAULT (getdate()),
             CONSTRAINT [PK_esolShopBestandQueue] PRIMARY KEY CLUSTERED ([id] ASC)
             )')



            SET ANSI_NULLS ON

            SET QUOTED_IDENTIFIER ON


            /* ggf. Dummy Trigger anlegen */
            if OBJECT_ID('tr_lbz_ins_ShopBestandQueue') is null
              exec('CREATE trigger [dbo].[tr_lbz_ins_ShopBestandQueue] on [dbo].[LagerBuchungsZeile] for insert,update as RETURN');
"@

        }
    }


    AfterAll {
        # Skip restore because for restoring you need special rights
        if (! $skipTest) {

            Restore-MssqlDatabase -udl $udl
        }
    }


    It 'Sets a new property element with an illegal article id' {
        if ($skipTest) {
            Set-ItResult -Skipped -Because 'This test should be skipped due to user not in sysadmin role'
            Return
        }

        $shop = Test-ShopExtension -udl $udl
        $shop | Should -BeFalse

        $myConn = Get-Conn -udl $udl
        $myConn.Execute($sqlShop)

        $shop = Test-ShopExtension -udl $udl
        $shop | Should -BeTrue

        $myConn.Close()
    }

}
